---
dir: "tmp"
limit: 33
buffer: 454545
tesseract: 1
download: 1
pdfcpu: 1
gs: 1
pdftotext: 1
convert: 1
pdftoppm: 1
png2jpg: 1
resize: 1
shafile: 1
watermark: 1
darkimage: 1
filedata: 3
shastring: 3
wjsonfile: 3
jpeg-quality: 80
progressive: true
