# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make build
      
    - name: Golang Static Analysis Checker
      # You may pin to the exact commit or the version.
      # uses: danhunsaker/golang-github-actions@a9bf048c038aa399eaaf89f42d5dac4f23718723
      uses: danhunsaker/golang-github-actions@v1.3.1
      with:
        # execute comma-separated command(s). [errcheck/fmt/imports/ineffassign/lint/misspell/sec/shadow/staticcheck/vet]
        run: vet,staticcheck,lint,imports,fmt,errcheck,ineffassign
